### ISSUE TITLE
Documentation on how to set /tree as the default instead of /lab

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-hpc#105]
Servers are launched to /lab and not /tree

**Comment by costrouc** [comment]
Think this may be releated to the jupyterhub 2.0 change https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html#selecting-a-user-interface.

**Comment by Adam-D-Lewis** [comment]
I tried setting the following in all.yaml in group_vars, but that didn't work.

```yaml
jupyterhub_custom:
  Spawner:
    environment:
      JUPYTERHUB_SINGLEUSER_APP: notebook.notebookapp.NotebookApp
```
I confirmed it's setting the environment variables by checking the following in a terminal within the singleuser jupyterlab: 
```bash
example-user@hpc02-test:~$ echo $JUPYTERHUB_SINGLEUSER_APP
notebook.notebookapp.NotebookApp
```
Documentation suggesting it might work
https://jupyterhub.readthedocs.io/en/stable/api/spawner.html?highlight=c.Spawner.env_keep#jupyterhub.spawner.Spawner.environment

I'll continue looking into this.  I think I should be able to just set the JUPYTERHUB_SINGLEUSER_APP environment variable on the jupyterhub instance since it's already included in c.Spawner.env_keep

**Comment by Adam-D-Lewis** [comment]
Also tried setting the following in jupyterhub_config.py, but doesn't work.
```
# set classic notebook as default
os.environ['JUPYTERHUB_SINGLEUSER_APP']='notebook.notebookapp.NotebookApp'
```

**Comment by Adam-D-Lewis** [comment]
Changing `c.QHubHPCSpawner.default_url = '/lab'` to `c.QHubHPCSpawner.default_url = '/tree'` and setting 
```
# set classic notebook as default
os.environ['JUPYTERHUB_SINGLEUSER_APP']='notebook.notebookapp.NotebookApp'
```
in jupyterhub_config.py seems to work.  Not sure if both are necessary or just one.

**Comment by Adam-D-Lewis** [comment]
Setting the following in group_vars/all.yaml works
```yaml
jupyterhub_custom:
  QHubHPCSpawner:
    default_url: '/tree'
  Spawner:
    environment:
      JUPYTERHUB_SINGLEUSER_APP: notebook.notebookapp.NotebookApp
```
